spring.application.name=scheme-matcher
spring.datasource.url=jdbc:postgresql://localhost:5432/scheme_matcher
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true